### ISSUE TITLE
No operation detected

### ISSUE THREAD

**Issue by sparthan15** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#13] opened 2022-05-24 23:25 UTC
Hi,  trying the openapi viewer i got an message saying that there is not operation in the spec. I change the packagesToScan as follow and  it works:

packagesToScan: se.magnus

As the openapi operations are in the api project, openapi can not found any operations. Than you

**Comment by magnus-larsson** [comment] 2022-05-27 13:27
Hello Charlie!

Thanks for reporting this error!

I have tried to reproduce the error asuming you are on chapter 5 "Adding an API Description Using OpenAPI" by follwoing the instructions in the book like:

```
export BOOK_HOME=~/Documents/Microservices-with-Spring-Boot-and-Spring-Cloud-2E
git clone https://github.com/PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E.git $BOOK_HOME

cd $BOOK_HOME/Chapter05
./gradlew build && docker-compose build && docker-compose up -d

./test-em-all.bash
```

When I open the OpenAPI viewer using the URL http://localhost:8080/openapi/swagger-ui.html I get te expected web page:

![Screenshot 2022-05-27 at 15 22 17](https://user-images.githubusercontent.com/1313727/170707893-06c2a219-cad0-4a2e-87db-8a700e4dca9a.png)

So, I can't reproduce the error you reported.

Have you changed anything in the code, e.g. upgrading some dependencies?

Can you repeat the exact commands as shown above and let me know if it works for you?

Regards,
Magnus.

**Comment by magnus-larsson** [comment] 2022-06-06 12:14
Since I haven’t received any updates on how to reproduce this error, I’ll close the issue.

**Closed by magnus-larsson** 2022-06-06 12:14 UTC
